### ISSUE TITLE
Tag is on wrong commit

### ISSUE THREAD

**Issue by tversteeg** [sunng87/cargo-release#158] opened 2019-10-08 08:25 UTC
When I release a minor version the tag is added to the "start next development iteration .." commit instead of the "version .." commit, for example:

```
commit ... (HEAD -> master, tag: v0.1.10, origin/master, origin/HEAD)

    (cargo-release) start next development iteration 0.1.11-alpha.0

commit ...

    (cargo-release) version 0.1.10
```

If this is on purpose, can it be configured in a way that the tag is added to the first commit instead of the second? This is currently breaking my CI setup.

**Comment by sunng87** [comment] 2019-10-08 08:38
This is weird. What version of `cargo-release` you were using? 
We do git tag before the version bump commit. 
If you check cargo-release's github page, you can find those tags on right commits.

**Comment by tversteeg** [comment] 2019-10-08 08:59
I'm currently at work, and I released this at home yesterday. I'm running Debian and I updated all cargo packages yesterday so it should be the current version (`0.12.4`). I can verify this later today.

**Comment by tversteeg** [comment] 2019-10-09 20:11
I was correct, I'm running `cargo-release 0.12.4` installed through `cargo`. My shell is Bash.

```
  Operating System: Debian GNU/Linux bullseye/sid
            Kernel: Linux 5.2.0-3-amd64
      Architecture: x86-64
             Shell: GNU bash, version 5.0.3
```

**Comment by epage** [comment] 2019-10-10 01:27
Could you also post any relevant `release.toml`s and the command line used in case we're hitting some weird scenario.

**Comment by tversteeg** [comment] 2019-10-11 08:00
The command line I used was just `cargo release`. I'm not using a custom `release.toml`.

**Comment by tversteeg** [comment] 2019-10-12 14:03
I've now just done another release on the same machine without updating and the tag is placed on the right position. The last release I went from `0.1.10-beta.3` to `0.1.10` and the tag was misplaced, now I went from `0.1.10` to `0.1.11` and the tag is placed correctly.

**Comment by epage** [comment] 2019-11-06 02:55
Going ahead and closing this since you couldn't reproduce this.  Feel free to re-open if you run into it again!

**Closed by epage** 2019-11-06 02:55 UTC
